name: ColaGom library
description: Code snippets
meta_description: "Talk is cheap. Show me the code."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://colagom.github.io'
google_analytics: 'UA-78906923-2'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://colagom.github.io'
author:         'Cola Gom'

plugins:
  - jekyll-gist